apiVersion: v1
data:
  GUNICORN_WORKERS_PER_CORE: "2"
  LOG_LEVEL: info
kind: ConfigMap
metadata:
  name: devops-demo-environment-vars
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: devops-demo
  name: devops-demo
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: devops-demo
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devops-demo
  name: devops-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-demo
  template:
    metadata:
      labels:
        app: devops-demo
    spec:
      automountServiceAccountToken: false
      containers:
      - envFrom:
        - configMapRef:
            name: devops-demo-environment-vars
            optional: true
        image: ghcr.io/paulorpdl/devops-demo@sha256:e952274cc8623a814a8831e29ed5bc186224ee1f7d464a16f0d5e3f16070622e
        livenessProbe:
          httpGet:
            path: /api/
            port: http
          initialDelaySeconds: 5
        name: devops-demo
        ports:
        - containerPort: 8000
          name: http
        readinessProbe:
          httpGet:
            path: /api/
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 1000m
            ephemeral-storage: 1Gi
            memory: 1Gi
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: devops-demo
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
  - resource:
      name: memory
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devops-demo
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-demo
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: devops-demo
            port:
              number: 8000
        path: /
        pathType: Prefix
