apiVersion: v1
kind: Service
metadata:
  labels:
    app: devops-demo
  name: devops-demo
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: devops-demo
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devops-demo
  name: devops-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-demo
  template:
    metadata:
      labels:
        app: devops-demo
    spec:
      automountServiceAccountToken: false
      containers:
      - image: ghcr.io/paulorpdl/devops-demo@sha256:0eeacf090f97e15205ae1079c81be037b1212f55ac0d8d0a92286dc723bb1b8e
        name: devops-demo
        ports:
        - containerPort: 8000
          name: http
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 1000m
            ephemeral-storage: 1Gi
            memory: 1Gi
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: devops-demo
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
  - resource:
      name: memory
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devops-demo
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-demo
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: devops-demo
            port:
              number: 8000
        path: /
        pathType: Prefix
